repo_url: https://github.com/Requisitos-de-Software/2023.2-Grupo04
repo_name: 2023.2-E-Titulo
site_url: https://requisitos-de-software.github.io/2023.2-Grupo04/


site_name: e-Título
nav:
  - Início: index.md
  - Documentação do Aplicativo: E-titulo/documentacaoetitulo.md
  - Atas:
    - Ata 01: atas/ata_reuniao_01.md
    - Ata 02: atas/ata_reuniao_02.md
    - Ata 03: atas/ata_reuniao_03.md
  - Apresentações: 
    - Apresentação 01: apresentacoes/apresentacao01.md
  - Planejamento:
    - Escolha do Aplicativo: planejamento/aplicativoEscolhido.md
    - Termos de Uso: planejamento/copiatermos.md
    - HeatMap: planejamento/heatmap.md
    - Cronograma: planejamento/cronograma.md
    - Ferramentas: planejamento/ferramentas.md
    - Metodologia: planejamento/metodologia.md
    - Rich Picture: planejamento/richpicture.md
  - Elicitação:
    - Técnicas de Elicitação:
      - Perfil do Usuário: Elicitacao/perfilDoUsuario.md
      - Personas: Elicitacao/Personas.md
      - Brainstorming: Elicitação/tecnicas/brainstorming.md
      - Entrevista: Elicitação/tecnicas/entrevista.md
      - Instropecção: Elicitação/tecnicas/instropeccao.md
      - Termo de Consentimento: Elicitação/tecnicas/ModeloTermoConsentimento.md
      - Questionário: Elicitação/tecnicas/questionario.md
      - Storytelling: Elicitação/tecnicas/storytelling.md
    - Técnicas de Priorização:
      - $100: Elicitação/priorizacao/$100.md
      - First Things First: Elicitação/priorizacao/firstThingsFirst.md
      - Three Level Scale: Elicitação/priorizacao/threeLevelScale



plugins:
  - search:
      lang:
        - pt
        - en

theme:
  name: material
  language: pt-BR
  logo: imgs/img.logo.jpg
  favicon: imgs/img.logo.jpg
  palette:
    - scheme: deep purple
      primary: yellow
      toggle:
        icon: material/circle-half-full
        name: noturno
    - scheme: slate
      primary: blue
      toggle:
        icon: material/circle-half-full
        name: claro  

#Extensions
