repo_url: https://github.com/Requisitos-de-Software/2023.2-Grupo04
repo_name: 2023.2-E-Titulo
site_url: https://requisitos-de-software.github.io/2023.2-Grupo04/


site_name: e-Título
nav:
  - Início: index.md
  - Documentação do Aplicativo: E-titulo/documentacaoetitulo.md
  - Teste: historiasdeusuario.md
  - Atas:
    - Ata 01: atas/ata_reuniao_01.md
    - Ata 02: atas/ata_reuniao_02.md
    - Ata 03: atas/ata_reuniao_03.md
    - Ata 04: atas/ata_reuniao_04.md
    - Ata 05: atas/ata_reuniao_05.md
    - Ata 06: atas/ata_reuniao_06.md
  - Apresentações: 
    - Apresentação 01: apresentacoes/apresentacao01.md
    - Apresentação 02: apresentacoes/apresentacao02.md
    - Apresentação 03: apresentacoes/apresentacao03.md    
  - Planejamento:
    - Escolha do Aplicativo: planejamento/aplicativoescolhido.md
    - Termos de Uso: planejamento/copiatermos.md
    - HeatMap: planejamento/heatmap.md
    - Cronograma Planejado: planejamento/cronogramaPlanejado.md
    - Cornograma Executado: planejamento/CronogramaExecutado.md
    - Ferramentas: planejamento/Ferramentas.md
    - Metodologia: planejamento/metodologia.md
    - Rich Picture: planejamento/richpicture.md
  - Elicitação:
    - Técnicas de Elicitação:
      - Perfil do Usuário: elicitacao/perfilDoUsuario.md
      - Personas: elicitacao/Personas.md
      - Brainstorming: elicitacao/tecnicas/brainstorming.md
      - Entrevista: elicitacao/tecnicas/entrevista.md
      - Instropecção: elicitacao/tecnicas/introspeccao.md
      - Termo de Consentimento: elicitacao/tecnicas/ModeloTermoConsentimento.md
      - Questionário: elicitacao/tecnicas/questionario.md
      - Storytelling: elicitacao/tecnicas/storytelling.md
    - Técnicas de Priorização:
      - $100: elicitacao/priorizacao/$100.md
      - First Things First: elicitacao/priorizacao/firstThingsFirst.md
      - Three Level Scale: elicitacao/priorizacao/threeLevelScale.md
  - Modelagem:
    - Casos de Uso: modelagem/casosdeuso.md
    - Especificação Suplementar: modelagem/especificacao-suplementar.md
    - Cenários: modelagem/Cenarios.md
    - Léxicos: modelagem/lexico



plugins:
  - search:
      lang:
        - pt
        - en

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - toc.integrate
    - content.tabs.link
    - content.code.copy
    - search.suggest
    - search.highlight
  language: pt-BR
  logo: elicitacao/imgs/img.logo.jpg
  favicon: elicitacao/imgs/img.logo.jpg
  palette:
    - scheme: deep purple
      primary: yellow
      toggle:
        icon: material/circle-half-full
        name: noturno
    - scheme: slate
      primary: blue
      toggle:
        icon: material/circle-half-full
        name: claro  

#Extensions
