repo_url: https://github.com/Requisitos-de-Software/2023.2-Grupo04
repo_name: 2023.2-E-Titulo
site_url: https://requisitos-de-software.github.io/2023.2-Grupo04/


site_name: e-Título
nav:
  - Início: index.md
  - e-Título: E-titulo/Documentação_e-titulo.md
  - Atas:
    - Ata 01: atas/ata_reuniao_01.md
    - Ata 02: atas/ata_reuniao_02.md
  - Planejamento: 
    - Cronograma: planejamento/cronograma.md
    - Ferramentas: planejamento/Ferramentas.md
    - Metodologia: planejamento/metodologia.md
    - Pré-Rastreabilidade: 
      - Rich Picture: planejamento/richpicture.md
    - Termos de Uso: planejamento/copiatermos.md


plugins:
  - search:
      lang:
        - pt
        - en
theme:
  name: material
  language: pt-BR
  palette:
    - scheme: deep purple
      primary: grey
      toggle:
        icon: material/circle-half-full
        name: noturno
    - scheme: slate
      primary: black
      toggle:
        icon: material/circle-half-full
        name: claro  
