repo_url: https://github.com/Requisitos-de-Software/2023.2-Grupo04
repo_name: 2023.2-Grupo04


site_name: Nome do App escolhido para o Projeto
nav:
  - Início: index.md


theme:
  name: material
  palette:
    - scheme: deep purple
      primary: grey
      toggle:
        icon: material/circle-half-full
        name: noturno
    - scheme: slate
      primary: black
      toggle:
        icon: material/circle-half-full
        name: claro  



