repo_url: https://github.com/Requisitos-de-Software/2023.2-Grupo04
repo_name: 2023.2-E-Titulo
site_url: https://requisitos-de-software.github.io/2023.2-Grupo04/


site_name: e-Título
nav:
  - Início: index.md
  - Documentação do Aplicativo: E-titulo/documentacaoetitulo.md
  - Atas:
    - Ata 01: atas/ata_reuniao_01.md
    - Ata 02: atas/ata_reuniao_02.md
    - Ata 03: atas/ata_reuniao_03.md
    - Ata 04: atas/ata_reuniao_04.md
    - Ata 05: atas/ata_reuniao_05.md
    - Ata 06: atas/ata_reuniao_06.md
    - Ata 07: atas/ata_reuniao_07.md
    - Ata 08: atas/ata_reuniao_08.md
    - Ata 09: atas/ata_reuniao_09.md
    - Ata 10: atas/ata_reuniao_10.md
    - Ata 11: atas/ata_reuniao_11.md   
    - Ata 12: atas/ata_reuniao_12.md   
  - Apresentações: 
    - Apresentação 01: apresentacoes/apresentacao01.md
    - Apresentação 02: apresentacoes/apresentacao02.md
    - Apresentação 03: apresentacoes/apresentacao03.md
    - Apresentação 04: apresentacoes/apresentacao04.md
    - Apresentação 05: apresentacoes/apresentacao05.md        
  - Planejamento:
    - Escolha do Aplicativo: planejamento/aplicativoescolhido.md
    - Termos de Uso: planejamento/copiatermos.md
    - HeatMap: planejamento/heatmap.md
    - Cronograma Planejado: planejamento/cronogramaPlanejado.md
    - Cornograma Executado: planejamento/CronogramaExecutado.md
    - Ferramentas: planejamento/Ferramentas.md
    - Metodologia: planejamento/metodologia.md
    - Rich Picture: planejamento/richpicture.md
  - Elicitação:
    - Técnicas de Elicitação:
      - Perfil do Usuário: elicitacao/perfilDoUsuario.md
      - Personas: elicitacao/Personas.md
      - Brainstorming: elicitacao/tecnicas/brainstorming.md
      - Entrevista: elicitacao/tecnicas/entrevista.md
      - Instropecção: elicitacao/tecnicas/introspeccao.md
      - Termo de Consentimento: elicitacao/tecnicas/ModeloTermoConsentimento.md
      - Questionário: elicitacao/tecnicas/questionario.md
      - Storytelling: elicitacao/tecnicas/storytelling.md
    - Técnicas de Priorização:
      - $100: elicitacao/priorizacao/$100.md
      - First Things First: elicitacao/priorizacao/firstThingsFirst.md
      - Three Level Scale: elicitacao/priorizacao/threeLevelScale.md
  - Modelagem:
    - Casos de Uso: modelagem/casosdeuso.md
    - Especificação Suplementar: modelagem/especificacao-suplementar.md
    - Cenários: modelagem/Cenarios.md
    - Léxicos: modelagem/lexico
  - Modelagem Ágil:
    - Histórias de Usuário: modelagem/agil/historiasdeusuario.md
    - Backlog: modelagem/agil/backlog.md
    - NFR Framework: modelagem/agil/nfr.md
  - Verificação:
    - Referências:
      - Etapa 1: verificacao/referenciasVerificacao/referenciasEtapa1.md
      - Etapa 2: verificacao/referenciasVerificacao/referenciasEtapa2.md
      - Etapa 3: verificacao/referenciasVerificacao/referenciasEtapa3.md
      - Etapa 4: verificacao/referenciasVerificacao/referenciasEtapa4.md
      - Etapa 6: verificacao/referenciasVerificacao/referenciasEtapa6.md
    - Verificação grupo 5:
      - Entrega 1:
        - Planejamento da Verificação da Primeira Entrega: verificacao/verificacaoGrupo+1/etapa1/PlanejamentoVerificacaoEtapa1.md
        - Apresentação: verificacao/verificacaoGrupo+1/etapa1/apresentacao.md
        - Cronograma: verificacao/verificacaoGrupo+1/etapa1/cronograma.md
        - Ferramentas: verificacao/verificacaoGrupo+1/etapa1/Ferramentas.md
        - Escolha do Aplicativo: verificacao/verificacaoGrupo+1/etapa1/escolha-do-aplicativo.md
        - Metodologia: verificacao/verificacaoGrupo+1/etapa1/metodologia.md
        - Rich Picture: verificacao/verificacaoGrupo+1/etapa1/richPicture.md
      - Entrega 2:
        - Planejamento da Verificação da Segunda Entrega: verificacao/verificacaoGrupo+1/etapa2/PlanejamentoVerificacaoEtapa2.md
        - Personas: verificacao/verificacaoGrupo+1/etapa2/personas.md
        - Perfil do Usuário: verificacao/verificacaoGrupo+1/etapa2/PerfilUsuario.md
        - Elicitação:
          - Brainstorming: verificacao/verificacaoGrupo+1/etapa2/brainstorming.md
          - Entrevista: verificacao/verificacaoGrupo+1/etapa2/entrevista.md
          - Observação: verificacao/verificacaoGrupo+1/etapa2/observacao.md
          - Itrospecção: verificacao/verificacaoGrupo+1/etapa2/Introspeccao.md
          - Questionário: verificacao/verificacaoGrupo+1/etapa2/questionario.md
        - Priorização:
          - First Things First: verificacao/verificacaoGrupo+1/etapa2/firstThingsFirst.md
          - MoSCoW: verificacao/verificacaoGrupo+1/etapa2/MoSCoW.md
          - Three Level Scale: verificacao/verificacaoGrupo+1/etapa2/TLS.md    
      - Entrega 3:
        - Planejamento da Verificação da Terceira Entrega: verificacao/verificacaoGrupo+1/etapa3/PlanejamentoVerificacaoEtapa3.md
        - Especificação Suplementar: verificacao/verificacaoGrupo+1/etapa3/especificacao-suplementar.md
        - Casos de uso: verificacao/verificacaoGrupo+1/etapa3/Casosdeuso.md
        - Cenários: verificacao/verificacaoGrupo+1/etapa3/cenarios.md
        - Léxicos: verificacao/verificacaoGrupo+1/etapa3/lexicos.md
      - Entrega 4:
        - Planejamento da Verificação da Terceira Entrega: verificacao/verificacaoGrupo+1/etapa4/PlanejamentoVerificacaoEtapa4.md
        - Backlog: verificacao/verificacaoGrupo+1/etapa4/backlog.md
        - Histórias de Usuário: verificacao/verificacaoGrupo+1/etapa4/historiasUsuario.md
        - NFR Framework: verificacao/verificacaoGrupo+1/etapa4/nfrFramework.md
    - Verificação grupo 4(e-Título):
      - Entrega 1:
        - Planejamento da Verificação da Primeira Entrega: verificacao/verificacaoGrupo4/etapa1/PlanejamentoVerificacaoEtapa1.md
        - Apresentação: verificacao/verificacaoGrupo4/etapa1/apresentacao.md
        - Cronograma: verificacao/verificacaoGrupo4/etapa1/cronograma.md
        - Ferramentas: verificacao/verificacaoGrupo4/etapa1/Ferramentas.md
        - Escolha do Aplicativo: verificacao/verificacaoGrupo4/etapa1/escolha-do-aplicativo.md
        - Metodologia: verificacao/verificacaoGrupo4/etapa1/metodologia.md
        - Rich Picture: verificacao/verificacaoGrupo4/etapa1/richPicture.md
      - Entrega 2:
        - Planejamento da Verificação da Segunda Entrega: verificacao/verificacaoGrupo4/etapa2/PlanejamentoVerificacaoEtapa2.md
        - Personas: verificacao/verificacaoGrupo4/etapa2/personas.md
        - Perfil do Usuário: verificacao/verificacaoGrupo4/etapa2/PerfilUsuario.md
        - Elicitação:
          - Brainstorming: verificacao/verificacaoGrupo4/etapa2/brainstorming.md
          - Entrevista: verificacao/verificacaoGrupo4/etapa2/entrevista.md
          - Itrospecção: verificacao/verificacaoGrupo4/etapa2/Introspeccao.md
          - Questionário: verificacao/verificacaoGrupo4/etapa2/questionario.md
          - Storytelling: verificacao/verificacaoGrupo4/etapa2/storytelling.md
        - Priorização:
          - 100$: verificacao/verificacaoGrupo4/etapa2/$100.md
          - First Things First: verificacao/verificacaoGrupo4/etapa2/firstThingsFirst.md
          - Three Level Scale: verificacao/verificacaoGrupo4/etapa2/TLS.md    
      - Entrega 3:
        - Planejamento da Verificação da Terceira Entrega: verificacao/verificacaoGrupo4/etapa3/PlanejamentoVerificacaoEtapa3.md
        - Especificação Suplementar: verificacao/verificacaoGrupo4/etapa3/especificacao-suplementar.md
        - Casos de uso: verificacao/verificacaoGrupo4/etapa3/Casosdeuso.md
        - Cenários: verificacao/verificacaoGrupo4/etapa3/cenarios.md
        - Léxicos: verificacao/verificacaoGrupo4/etapa3/lexicos.md
      - Entrega 4:
        - Planejamento da Verificação da Quarta Entrega: verificacao/verificacaoGrupo4/etapa4/PlanejamentoVerificacaoEtapa4.md
        - Backlog: verificacao/verificacaoGrupo4/etapa4/backlog.md
        - Histórias de Usuário: verificacao/verificacaoGrupo4/etapa4/historiasUsuario.md
        - NFR Framework: verificacao/verificacaoGrupo4/etapa4/nfrFramework.md
      - Entrega 6:
        - Planejamento da Verificação da Sexta Entrega: verificacao/verificacaoGrupo4/etapa6/PlanejamentoVerificacaoEtapa6.md
        - Backward-from: verificacao/verificacaoGrupo4/etapa6/backwardFrom.md
        - Forward-from: verificacao/verificacaoGrupo4/etapa6/forwardFrom.md
        - Matriz de Rastreabilidade: verificacao/verificacaoGrupo4/etapa6/matriz.md

  - Pós Rastreabilidade:
    - Backward-from: pos-rastreabilidade/backwardFrom.md
    - Forward-from: pos-rastreabilidade/forwardFrom.md
    - Matriz de Rastreabilidade: pos-rastreabilidade/matriz.md

  - Validação:
    - Consolidações: validacao/consolidacoes.md
    - Informal: validacao/informal.md
    - Validação do protótipo: validacao/validacaoPrototipo.md

plugins:
  - search:
      lang:
        - pt
        - en

theme:
  name: material
  features:
    - navigation.tabs

  language: pt-BR
  logo: elicitacao/imgs/img.logo.jpg
  favicon: elicitacao/imgs/img.logo.jpg
  palette:
    - scheme: deep purple
      primary: yellow
      toggle:
        icon: material/circle-half-full
        name: noturno
    - scheme: slate
      primary: blue
      toggle:
        icon: material/circle-half-full
        name: claro  

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
