repo_url: https://github.com/Requisitos-de-Software/2023.2-Grupo04
repo_name: 2023.2-Grupo04


site_name: Nome do App escolhido para o Projeto
nav:
  - Início: index.md
  - Apresentação:
    - Apresentação Teste: apresentacoes/apresentacaoTeste.md
  - Atas:
    - Ata Teste: atas/ataTeste.md
  - Planejamento:
    - Planejamento Teste: planejamento/planejamentoTeste.md

plugins:
  - search:
      lang:
        - pt
        - en

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: deep purple
      primary: grey
      toggle:
        icon: material/circle-half-full
        name: noturno
    - scheme: slate
      primary: black
      toggle:
        icon: material/circle-half-full
        name: claro  



